#!/usr/bin/env bash
# Read kbase.volumes and emit docker-compose.kbase.generated.yml for merging with any scenario compose file.
# Usage (from Progento_SelfHosted repo root): ./scripts/gen-kbase-compose.sh
# Env: KBASE_VOLUMES_FILE=path (default: kbase.volumes in repo root)
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

INPUT="${KBASE_VOLUMES_FILE:-kbase.volumes}"
OUT="docker-compose.kbase.generated.yml"

rm -f "$OUT"

if [ ! -f "$INPUT" ]; then
  echo "No ${INPUT} — ${OUT} not created (optional KBase mounts off)."
  exit 0
fi

valid=0
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

while IFS= read -r line || [ -n "${line:-}" ]; do
  # strip comments (everything after unescaped # not ideal; use leading # only)
  case "$line" in
    \#*|'') continue ;;
  esac
  line="${line%%#*}"
  line="${line#"${line%%[![:space:]]*}"}"
  line="${line%"${line##*[![:space:]]}"}"
  [ -z "$line" ] && continue
  if [[ "$line" != *:/kbase/* ]]; then
    echo "Warning: skip (container path must contain ':/kbase/'): $line" >&2
    continue
  fi
  echo "$line" >> "$tmp"
  valid=$((valid + 1))
done < "$INPUT"

if [ "$valid" -eq 0 ]; then
  echo "No valid lines in ${INPUT} — removed ${OUT} if it existed."
  exit 0
fi

{
  echo "# Generated by scripts/gen-kbase-compose.sh from ${INPUT} — do not edit by hand."
  echo "# Re-run: ./scripts/gen-kbase-compose.sh"
  echo "services:"
  echo "  api:"
  echo "    volumes:"
  while IFS= read -r vol; do
    echo "      - ${vol}"
  done < "$tmp"
} > "$OUT"

echo "Wrote ${OUT} (${valid} mount(s)) from ${INPUT}."
